name: event_emitter
description: Event tools inspired by NodeJS.
version: 1.0.0
repository: http://thispage.tech:9680/jclee1995/event_emitter
issue_tracker: http://thispage.tech:9680/jclee1995/event_emitter/issues
auth:
  name: jcaklee
  email: 291148484@163.com
  home: http://thispage.tech

environment:
  sdk: ^3.0.5

dev_dependencies:
  lints: ^2.0.0
